### ISSUE TITLE
escaping of < and >

### ISSUE THREAD

**Issue by myrrhlin** [nigelm/html-scrubber#1]
hi nigel,

$ perl -MHTML::Scrubber -e '$s=HTML::Scrubber->new(); print $s->scrub(qq[ Y U escape > & <, HTML::Scrubber? \n])'
 Y U escape &amp;gt; & &amp;lt;, HTML::Scrubber?

this behavior caused me trouble.  people often use > for quoting in, e.g., email.  

i am not the only one who's had this issue:
   https://rt.cpan.org/Public/Bug/Display.html?id=69947

it's debatable whether this behavior is "correct" :  HTML::Scrubber is used to remove HTML tags of various kinds -- but here it's escaping an entity that, although it might confuse some parser, is not part of any HTML.  there appears no option to turn off this behavior.

the guilty lines appear to be 440-441:
        $text =~ s/</&amp;lt;/g;    #https://rt.cpan.org/Ticket/Attachment/8716/10332/scrubber.patch
        $text =~ s/>/&amp;gt;/g;

The comment suggests this behavior was added to address some issue.

In the changelog for HTML::Scrubber, there is the following:
0.03  Mon Jul 21 07:32:10 2003
    - closed http://rt.cpan.org/NoAuth/Bug.html?id=2969
      now escape spurious >< in text

I searched for the relevant RT ticket to understand why this change was made, but couldn't find it.  It's not 8716, 10332, or 2969.

good luck.

michael

**Comment by nigelm** [comment]
At present I am going to come down on the side that fixing up stuff that isn't html at all is probably not a good use case.
